/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "RPC_xFile.h"

bool_t
xdr_Input (XDR *xdrs, Input *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, &objp->nomeDirettorio, NOMEDIRETTORIO_LENGTH))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_MyFile (XDR *xdrs, MyFile *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_vector (xdrs, (char *)objp->filename, FILENAME_LENGTH,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_OutputArray (XDR *xdrs, OutputArray *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_int (xdrs, &objp->errore))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->nFiles))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->files, NUM_FILES,
		sizeof (MyFile), (xdrproc_t) xdr_MyFile))
		 return FALSE;
	return TRUE;
}
