/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _RPC_XFILE_H_RPCGEN
#define _RPC_XFILE_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif

#define ID_LENGTH 10
#define CITTA_LENGTH 20

struct InputStruct {
	char *id;
	int ritardo;
};
typedef struct InputStruct InputStruct;

typedef struct OutputStruct *OutputList;

struct OutputStruct {
	char *id;
	char *partenza;
	char *arrivo;
	int orarioAttesa_ora;
	int orarioAttesa_minuti;
	int ritardo;
	OutputList next;
};
typedef struct OutputStruct OutputStruct;

#define ESAMEPROG 0x20000069
#define ESAMEVERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define VISUALIZZA_LISTA 1
extern  OutputList * visualizza_lista_1(char **, CLIENT *);
extern  OutputList * visualizza_lista_1_svc(char **, struct svc_req *);
#define MODIFICA_RITARDO_VIAGGO 2
extern  int * modifica_ritardo_viaggo_1(InputStruct *, CLIENT *);
extern  int * modifica_ritardo_viaggo_1_svc(InputStruct *, struct svc_req *);
extern int esameprog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define VISUALIZZA_LISTA 1
extern  OutputList * visualizza_lista_1();
extern  OutputList * visualizza_lista_1_svc();
#define MODIFICA_RITARDO_VIAGGO 2
extern  int * modifica_ritardo_viaggo_1();
extern  int * modifica_ritardo_viaggo_1_svc();
extern int esameprog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_InputStruct (XDR *, InputStruct*);
extern  bool_t xdr_OutputList (XDR *, OutputList*);
extern  bool_t xdr_OutputStruct (XDR *, OutputStruct*);

#else /* K&R C */
extern bool_t xdr_InputStruct ();
extern bool_t xdr_OutputList ();
extern bool_t xdr_OutputStruct ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_RPC_XFILE_H_RPCGEN */
