/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "RPC_xFile.h"

bool_t
xdr_InputStruct (XDR *xdrs, InputStruct *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, &objp->id, ID_LENGTH))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->ritardo))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_OutputList (XDR *xdrs, OutputList *objp)
{
	register int32_t *buf;

	 if (!xdr_pointer (xdrs, (char **)objp, sizeof (struct OutputStruct), (xdrproc_t) xdr_OutputStruct))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_OutputStruct (XDR *xdrs, OutputStruct *objp)
{
	register int32_t *buf;


	if (xdrs->x_op == XDR_ENCODE) {
		 if (!xdr_string (xdrs, &objp->id, ID_LENGTH))
			 return FALSE;
		 if (!xdr_string (xdrs, &objp->partenza, CITTA_LENGTH))
			 return FALSE;
		 if (!xdr_string (xdrs, &objp->arrivo, CITTA_LENGTH))
			 return FALSE;
		buf = XDR_INLINE (xdrs, 3 * BYTES_PER_XDR_UNIT);
		if (buf == NULL) {
			 if (!xdr_int (xdrs, &objp->orarioAttesa_ora))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->orarioAttesa_minuti))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->ritardo))
				 return FALSE;

		} else {
		IXDR_PUT_LONG(buf, objp->orarioAttesa_ora);
		IXDR_PUT_LONG(buf, objp->orarioAttesa_minuti);
		IXDR_PUT_LONG(buf, objp->ritardo);
		}
		 if (!xdr_OutputList (xdrs, &objp->next))
			 return FALSE;
		return TRUE;
	} else if (xdrs->x_op == XDR_DECODE) {
		 if (!xdr_string (xdrs, &objp->id, ID_LENGTH))
			 return FALSE;
		 if (!xdr_string (xdrs, &objp->partenza, CITTA_LENGTH))
			 return FALSE;
		 if (!xdr_string (xdrs, &objp->arrivo, CITTA_LENGTH))
			 return FALSE;
		buf = XDR_INLINE (xdrs, 3 * BYTES_PER_XDR_UNIT);
		if (buf == NULL) {
			 if (!xdr_int (xdrs, &objp->orarioAttesa_ora))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->orarioAttesa_minuti))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->ritardo))
				 return FALSE;

		} else {
		objp->orarioAttesa_ora = IXDR_GET_LONG(buf);
		objp->orarioAttesa_minuti = IXDR_GET_LONG(buf);
		objp->ritardo = IXDR_GET_LONG(buf);
		}
		 if (!xdr_OutputList (xdrs, &objp->next))
			 return FALSE;
	 return TRUE;
	}

	 if (!xdr_string (xdrs, &objp->id, ID_LENGTH))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->partenza, CITTA_LENGTH))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->arrivo, CITTA_LENGTH))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->orarioAttesa_ora))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->orarioAttesa_minuti))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->ritardo))
		 return FALSE;
	 if (!xdr_OutputList (xdrs, &objp->next))
		 return FALSE;
	return TRUE;
}
