/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _RPC_XFILE_H_RPCGEN
#define _RPC_XFILE_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif

#define NOMEDIRETTORIO_LENGTH 50
#define PREFISSO_LENGTH 10
#define FILENAME_LENGTH 50

struct Input {
	char *nomeDirettorio;
	char *prefisso;
};
typedef struct Input Input;

typedef struct OutputStruct *OutputList;

struct OutputStruct {
	char *filename;
	OutputList next;
};
typedef struct OutputStruct OutputStruct;

struct Result {
	int errore;
	union {
		OutputList list;
	} Result_u;
};
typedef struct Result Result;

#define ESAMEPROG 0x20042069
#define ESAMEVERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define CONTA_OCCORRENZE_LINEA 1
extern  int * conta_occorrenze_linea_1(char **, CLIENT *);
extern  int * conta_occorrenze_linea_1_svc(char **, struct svc_req *);
#define LISTA_FILE_PREFISSO 2
extern  Result * lista_file_prefisso_1(Input *, CLIENT *);
extern  Result * lista_file_prefisso_1_svc(Input *, struct svc_req *);
extern int esameprog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define CONTA_OCCORRENZE_LINEA 1
extern  int * conta_occorrenze_linea_1();
extern  int * conta_occorrenze_linea_1_svc();
#define LISTA_FILE_PREFISSO 2
extern  Result * lista_file_prefisso_1();
extern  Result * lista_file_prefisso_1_svc();
extern int esameprog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_Input (XDR *, Input*);
extern  bool_t xdr_OutputList (XDR *, OutputList*);
extern  bool_t xdr_OutputStruct (XDR *, OutputStruct*);
extern  bool_t xdr_Result (XDR *, Result*);

#else /* K&R C */
extern bool_t xdr_Input ();
extern bool_t xdr_OutputList ();
extern bool_t xdr_OutputStruct ();
extern bool_t xdr_Result ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_RPC_XFILE_H_RPCGEN */
