/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "RPC_xFile.h"

bool_t
xdr_Input (XDR *xdrs, Input *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, &objp->nomeDirettorio, NOMEDIRETTORIO_LENGTH))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->prefisso, PREFISSO_LENGTH))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_OutputList (XDR *xdrs, OutputList *objp)
{
	register int32_t *buf;

	 if (!xdr_pointer (xdrs, (char **)objp, sizeof (struct OutputStruct), (xdrproc_t) xdr_OutputStruct))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_OutputStruct (XDR *xdrs, OutputStruct *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, &objp->filename, FILENAME_LENGTH))
		 return FALSE;
	 if (!xdr_OutputList (xdrs, &objp->next))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_Result (XDR *xdrs, Result *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->errore))
		 return FALSE;
	switch (objp->errore) {
	case 0:
		 if (!xdr_OutputList (xdrs, &objp->Result_u.list))
			 return FALSE;
		break;
	default:
		break;
	}
	return TRUE;
}
